import { Destination, TravelPackage, Reservation, Review } from './types';

export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'dest-santorini',
    name: 'Santorini',
    country: 'Grécia',
    price: 3200,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBcxLmCxg6gksIOtNaqOk6Yh2vEIsmtHAtnx9baol1BkCg1BkMRKcEf-EIbjttTw_ocLwLPb8JzdMf01IpWFbnBK6Vnli8IcMFfaEhGf91WrSVwdGmTcVUrEcJWluVA4X4m5GRiL0g005fOyZN4x5aDAxmfMNrODGHMXn7bVJYrNSfxt6IscnmnNyL-eNxT1Fu-CsPjkj09eXyaNO6yNJmDqiWiDkICQpD3TBlyQmk1KcCfUUlkOxq0Xb7Kjv8x7xWGyP4o_zPz2Ho',
    description: 'Pôr do sol inesquecível, arquitetura icônica e praias de areia vulcânica em uma ilha deslumbrante no mar Egeu.',
    bestSeason: 'Mai - Out',
    rating: 4.9,
    lat: 36.412,
    lng: 25.432
  },
  {
    id: 'dest-cairo',
    name: 'Cairo',
    country: 'Egito',
    price: 2800,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCDMtYmJka_fDX64EZLl5oiIUr9OxcE_PZECEkFXv1_VoCubaqtDL_kFcX6S29y9LeJ2sXzn7XlRldzklDebD_DvPog8RNa45BCUEOV4ezQlIHF8wFX4BLXJ_Av0vzieR6sKf3wSDh9ktl71B9Buf-EFA-WXy_V4pLm7xnnLontnQFgnwsjBh-SOZZizVjtlVHH2RWO4S4uD-NjpR-kFRjMd5e-A9HEs1lVA05uNvVBSxg09BzmOuU_43n6VEee5388uAerXTayvk4',
    description: 'Explore os mistérios dos faraós, as Grandes Pirâmides e navegue pelas águas históricas do rio Nilo com total exclusividade.',
    bestSeason: 'Out - Abr',
    rating: 4.8,
    lat: 30.044,
    lng: 31.235
  },
  {
    id: 'dest-zermatt',
    name: 'Zermatt',
    country: 'Suíça',
    price: 4500,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC8QNNGb3O2zSJcWhP649biUy-gGwRKV497nZSyhYi-pUBDoIm7Z62j4Qb6qo2-60U_YIlcW7NlkdF5KrHN648wSEQIcHPZuWUddI81kwejrRdx3rNhRL0A_KCRZge8xj9_TpbSz1VWVKJvD64bIVL9K-uhuFiC87KLTrQq9QnU5il4Hv37n08NNNTQITd3jclsg2MCcbyLIBdGYJAtltOD9MxKd_GnAGdUo5CCuPSbnSKqDR-S5ebRtolN0Wd_DyHHpkLZHfuxW7A',
    description: 'Elegância nos Alpes, resorts de esqui de classe mundial e vistas panorâmicas do majestoso Matterhorn.',
    bestSeason: 'Dez - Mar',
    rating: 4.5,
    lat: 46.02,
    lng: 7.749
  },
  {
    id: 'dest-noronha',
    name: 'Fernando de Noronha',
    country: 'Brasil',
    price: 2100,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCAWf3Bb-eOWOU206RqsUxC3E1Su2NZhErJOyeGlPP6oNvKgJnkAmKZBfDIcad_N3QMjPQRdnz36KxRDQHEkwNRqFs1isbVf-uhzVigVzyBVFvGcqo0nMRUon8lirfGq3KqAibIf97smddCbJd54ZzHQVcKSppr9u14FY6GPyWULz-GKQGJvlATjLdMWI0fGDWTlJtdQxz_bGjXSRD2b2PRPsY5dH1nmiHFctgZpNWbyVCQvtxgtW6HLRLf52qK_cLpIu2eXAdda_Y',
    description: 'Santuário ecológico intocado com as praias mais belas do mundo, ideal para mergulho e imersão na natureza.',
    bestSeason: 'Ago - Dez',
    rating: 4.7,
    lat: -3.854,
    lng: -32.426
  },
  {
    id: 'dest-angra',
    name: 'Angra dos Reis',
    country: 'Brasil',
    price: 1950,
    image: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=800&auto=format&fit=crop&q=80',
    description: 'Águas verde-esmeralda, ilhas exclusivas de areia branca e iates luxuosos no litoral sul fluminense.',
    bestSeason: 'Dez - Mar',
    rating: 4.8,
    lat: -23.001,
    lng: -44.318
  },
  {
    id: 'dest-bora-bora',
    name: 'Bora Bora',
    country: 'Polinésia Francesa',
    price: 5200,
    image: 'https://images.unsplash.com/photo-1505881502353-a1986add3762?w=800&auto=format&fit=crop&q=80',
    description: 'Bangalôs sobre a água nas lagoas mais turquesas do mundo sob picos icônicos tropicais.',
    bestSeason: 'Mai - Out',
    rating: 4.9,
    lat: -16.5,
    lng: -151.741
  }
];

export const INITIAL_PACKAGES: TravelPackage[] = [
  {
    id: 'pkg-santorini',
    title: 'Escapada Clássica no Egeu',
    destination: 'Santorini',
    country: 'Grécia',
    hotel: 'Katikies Hotel',
    stars: 5,
    flight: 'Voo Direto (TAP)',
    durationDays: 7,
    durationNights: 6,
    originalPrice: 16200,
    currentPrice: 14500,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6HrPepSNIBuUp8XhkhYjITDlj_bBK2XRV8mySCqZqN1937RIns8PBTc6ETGY6xtSrdDBicTTu_5TujCVZIy60hIsO8VtzNws5kq7Cp4CXVLATn1KRGNhTyhXTEOU6I1dDU1LG7ftIJbsuZ_bl28EfKjPBai1RJuSpq8Q23oU4mRK7UWosdbHzTpsdYHbLGkIiLOMG8NyT4lvbDkyP-K6vgKYGL08DzfOnTVTGqhty8ZJ2Vu7V6Ep6XxeKScRHfI3SbVAs75ubKQc',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB6HrPepSNIBuUp8XhkhYjITDlj_bBK2XRV8mySCqZqN1937RIns8PBTc6ETGY6xtSrdDBicTTu_5TujCVZIy60hIsO8VtzNws5kq7Cp4CXVLATn1KRGNhTyhXTEOU6I1dDU1LG7ftIJbsuZ_bl28EfKjPBai1RJuSpq8Q23oU4mRK7UWosdbHzTpsdYHbLGkIiLOMG8NyT4lvbDkyP-K6vgKYGL08DzfOnTVTGqhty8ZJ2Vu7V6Ep6XxeKScRHfI3SbVAs75ubKQc',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCw7Q_OoaothNvyAVWSYqhNTcxEj8eLaaDsOQ7CjTG_lD26DjfdHhIvBLgGowSDUkZQc8saAf_a0xgezviEusEzfhvrRetJVn6IUC7USMi2x_1dfKEk-RXaxg2QomrfycVcAD3HXGZZDaQ3AK05uy1JooHEvpoEDv4b4TOhdnMQwXF33uj9t8J6bG4BvLHTR5yV0ifyqhT6Xji7B_LzrXuN1ml-W7dW86RmtbRJS0GmcU0bxaCrwfHJthk3PXZye0Wht3n5OSW-DTg',
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&auto=format&fit=crop&q=80'
    ],
    rating: 4.9,
    reviewsCount: 128,
    description: 'Vivencie o epítome do romance grego. Desfrute da inigualável arquitetura branca e cúpulas azuis no Katikies Hotel, com vistas panorâmicas sobre a caldeira do vulcão e pôr do sol lendário de Oia.',
    accommodation: {
      name: 'Katikies Hotel Santorini',
      stars: 5,
      description: 'Aninhado nas falésias dramáticas de Oia, o Katikies Hotel oferece suítes de luxo esculpidas na rocha vulcânica com piscinas infinitas privativas aquecidas e serviço de mordomo dedicado.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCw7Q_OoaothNvyAVWSYqhNTcxEj8eLaaDsOQ7CjTG_lD26DjfdHhIvBLgGowSDUkZQc8saAf_a0xgezviEusEzfhvrRetJVn6IUC7USMi2x_1dfKEk-RXaxg2QomrfycVcAD3HXGZZDaQ3AK05uy1JooHEvpoEDv4b4TOhdnMQwXF33uj9t8J6bG4BvLHTR5yV0ifyqhT6Xji7B_LzrXuN1ml-W7dW86RmtbRJS0GmcU0bxaCrwfHJthk3PXZye0Wht3n5OSW-DTg',
      amenities: ['Piscina Infinita', 'Serviço de Borda Líquida', 'Restaurante Michelin', 'Mordomo 24h']
    },
    itinerary: [
      { day: 1, title: 'Chegada VIP e Sunset Drink', description: 'Recepção VIP no aeroporto de Santorini com transfer executivo. Check-in na suíte luxo e brinde de boas-vindas ao pôr do sol.' },
      { day: 2, title: 'Cruzeiro Privativo em Catamarã', description: 'Explore a Caldeira de Santorini em um veleiro privativo com mergulho nas águas termais e almoço gourmet de frutos do mar a bordo.' },
      { day: 3, title: 'Degustação Histórica em Vinícolas Assadas', description: 'Tour de destilados e vinhos raros vulcânicos acompanhado de sommelier particular em vinícola escavada em caverna.' }
    ],
    includedExperiences: [
      { icon: 'scuba_diving', title: 'Mergulho na Caldeira', description: 'Exploração subaquática guiada por águas termais enriquecidas do vulcão.' },
      { icon: 'sailing', title: 'Sunset Private Cruise', description: 'Navegação ao entardecer sob as falésias douradas com chef exclusivo.' }
    ]
  },
  {
    id: 'pkg-dubai',
    title: 'Luxo Urbano e Deserto',
    destination: 'Dubai',
    country: 'EAU',
    hotel: 'Atlantis The Palm',
    stars: 5,
    flight: 'Emirates Airlines',
    durationDays: 5,
    durationNights: 4,
    originalPrice: 21000,
    currentPrice: 18200,
    isPromo: true,
    promoLabel: 'PROMOÇÃO',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEUvRw9djQBIxsjcLWPAx738ZPnjdZNR5omJTEtGfnn9MapB4_CCeDnC1612uNSJPP0sKeczGtKa8klgkt2VkBld03wLFA9FBzRro7O_ba1lXnOTOmdcjN5-khaBEnfaDzjh3f2gts_ygcKv3tqJpYReAmvEdMaIEGR5M4PCt_n-LW6q2hkSXuNvj03qWr7edWi_uWzQigf5GiF6M5D4WFCl5hUt2Oegca3N1RpNDqE9y3ZQNU1ujdtrDxz9nH0gWfTSgzzE_psk4',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDEUvRw9djQBIxsjcLWPAx738ZPnjdZNR5omJTEtGfnn9MapB4_CCeDnC1612uNSJPP0sKeczGtKa8klgkt2VkBld03wLFA9FBzRro7O_ba1lXnOTOmdcjN5-khaBEnfaDzjh3f2gts_ygcKv3tqJpYReAmvEdMaIEGR5M4PCt_n-LW6q2hkSXuNvj03qWr7edWi_uWzQigf5GiF6M5D4WFCl5hUt2Oegca3N1RpNDqE9y3ZQNU1ujdtrDxz9nH0gWfTSgzzE_psk4',
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80'
    ],
    rating: 4.8,
    reviewsCount: 94,
    description: 'Experimente a opulência extravagante do Atlantis The Palm em Dubai. Desde parques aquáticos futuristas, gastronomia com estrelas Michelin, até safáris dourados nas dunas privativas do deserto.',
    accommodation: {
      name: 'Atlantis The Palm Dubai',
      stars: 5,
      description: 'O resort de cinco estrelas definitivo, coroando a icônica ilha de Palm Jumeirah. Apresenta o maior aquário do mundo, praias particulares de areia macia e quartos subaquáticos majestosos.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEUvRw9djQBIxsjcLWPAx738ZPnjdZNR5omJTEtGfnn9MapB4_CCeDnC1612uNSJPP0sKeczGtKa8klgkt2VkBld03wLFA9FBzRro7O_ba1lXnOTOmdcjN5-khaBEnfaDzjh3f2gts_ygcKv3tqJpYReAmvEdMaIEGR5M4PCt_n-LW6q2hkSXuNvj03qWr7edWi_uWzQigf5GiF6M5D4WFCl5hUt2Oegca3N1RpNDqE9y3ZQNU1ujdtrDxz9nH0gWfTSgzzE_psk4',
      amenities: ['Parque Aquático', 'Suíte Subaquática', 'Gastronomia Michelin', 'Heliponto Privado']
    },
    itinerary: [
      { day: 1, title: 'Boas-Vindas Reais em Palm Jumeirah', description: 'Recepção com limusine no aeroporto internacional e check-in exclusivo. Jantar VIP com vista para o aquário flutuante.' },
      { day: 2, title: 'Aventura Real no Deserto', description: 'Safári de SUV 4x4 gourmet com falcoaria clássica, passeio de camelo de elite e banquete em tenda luxuosa de tapetes persas.' },
      { day: 3, title: 'Helicóptero City Premium Tour', description: 'Voo panorâmico de helicóptero sobre as maiores maravilhas da engenharia humana, Burj Khalifa e Palm Islands.' }
    ],
    includedExperiences: [
      { icon: 'scuba_diving', title: 'Aquarium Dive Pro', description: 'Mergulho de cilindro no majestoso tanque do aquário gigante entre tubarões.' },
      { icon: 'explore', title: 'Desert Golden Safari', description: 'Aventura nas dunas vermelhas com acampamento beduíno estrelado premium.' }
    ]
  },
  {
    id: 'pkg-maldivas',
    title: 'Paraíso Intocado',
    destination: 'Maldivas',
    country: 'Maldivas',
    hotel: 'Soneva Jani Resort',
    stars: 5,
    flight: 'Qatar Airways',
    durationDays: 10,
    durationNights: 9,
    originalPrice: 39500,
    currentPrice: 35800,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDfosPS1TtLc_IRnEP0BJRg3J39LMPsNXSKJRakAcKUQlZi2sy9_NWtX2oqXBaLCUFnwNQjDwbG0DsMfICJ0vgWpvUG2-4nK86vuWr2UilFU2UeysY2pnoG-ZbYD7upDBOWhhUmQyB4ksx2xmx9VmrFHLa2U1JoSN07MeQP6woIxCnZzbOT_mUCzB81yvQsB7SIsnIn8tiZcAGBiBLn_Sw0sO9OObR0GyqTV7R2t2WfxgZjAmPAycuFf_rtwNENycmjZzbaj20WQms',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDfosPS1TtLc_IRnEP0BJRg3J39LMPsNXSKJRakAcKUQlZi2sy9_NWtX2oqXBaLCUFnwNQjDwbG0DsMfICJ0vgWpvUG2-4nK86vuWr2UilFU2UeysY2pnoG-ZbYD7upDBOWhhUmQyB4ksx2xmx9VmrFHLa2U1JoSN07MeQP6woIxCnZzbOT_mUCzB81yvQsB7SIsnIn8tiZcAGBiBLn_Sw0sO9OObR0GyqTV7R2t2WfxgZjAmPAycuFf_rtwNENycmjZzbaj20WQms',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDh8-OCPmWgD2ZOXZmfFrQTy2fuS8O1ft-4WZMag8lxvZ9VF8axXKc2oeY3RC5OdQzVBxI74H2QQxj84egFZi9sZPM69QKXpWOAvl1_5H1VDD0VutHvn1mfyFS_-Q1PxBz7v5QeILlcw_zVAyu6FSnvq-I-K88nt95dMobJRjwaZ4BQdCzXtnrsh7AItVqRNczp0zkQnTDa1AhsxBxMnqApYXqpBLuk5oKH0lKiyfO5Ap6L2QblIe9ruLQfazJ5l4iHiDp0sL9vOss',
      'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=1200&auto=format&fit=crop&q=80'
    ],
    rating: 5.0,
    reviewsCount: 342,
    description: 'Desconecte-se de tudo nas majestosas águas turquesas do arquipélago das Maldivas. Usufrua de uma villa de dois andares com escorregador direto para a lagoa de coral azul elétrico.',
    accommodation: {
      name: 'Soneva Jani Resort Maldivas',
      stars: 5,
      description: 'Water Retreat de 1 Quarto com escorregador direto para a lagoa cristalina, teto retrátil sobre a cama master para observar as constelações equatoriais, e piscina particular suspensa com vista infinita.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDh8-OCPmWgD2ZOXZmfFrQTy2fuS8O1ft-4WZMag8lxvZ9VF8axXKc2oeY3RC5OdQzVBxI74H2QQxj84egFZi9sZPM69QKXpWOAvl1_5H1VDD0VutHvn1mfyFS_-Q1PxBz7v5QeILlcw_zVAyu6FSnvq-I-K88nt95dMobJRjwaZ4BQdCzXtnrsh7AItVqRNczp0zkQnTDa1AhsxBxMnqApYXqpBLuk5oKH0lKiyfO5Ap6L2QblIe9ruLQfazJ5l4iHiDp0sL9vOss',
      amenities: ['Wi-Fi Premium', 'Spa Terapêutico', 'Piscina Privada', 'Mordomo 24h']
    },
    itinerary: [
      { day: 1, title: 'Chegada e Recepção VIP', description: 'Chegada no Aeroporto Internacional de Malé. Recepção exclusiva no lounge da Soneva com bebidas de boas-vindas, seguida de traslado em hidroavião panorâmico até o resort. Check-in na sua Water Villa.' },
      { day: 2, title: 'Exploração Submarina', description: 'Manhã dedicada ao mergulho guiado por biólogos marinhos nos recifes próximos. Tarde livre para aproveitar a piscina privativa. Jantar sob as estrelas no observatório do resort.' },
      { day: 3, title: 'Relaxamento Profundo', description: 'Sessão matinal de yoga à beira-mar. À tarde, tratamento de assinatura de 90 minutos no Soneva Spa. Cruzeiro ao pôr do sol em um dhoni tradicional com champanhe e canapés.' }
    ],
    includedExperiences: [
      { icon: 'scuba_diving', title: 'Snorkeling em Recife Privativo', description: 'Equipamento premium e guia especializado para explorar a biodiversidade local.' },
      { icon: 'sailing', title: 'Cruzeiro ao Pôr do Sol', description: 'Navegação em barco tradicional com serviço de espumante e aperitivos finos.' }
    ]
  },
  {
    id: 'pkg-zermatt',
    title: 'Retiro Alpino Exclusivo',
    destination: 'Zermatt',
    country: 'Suíça',
    hotel: 'Mont Cervin Palace',
    stars: 4,
    flight: 'Swiss Int. Airlines',
    durationDays: 6,
    durationNights: 5,
    originalPrice: 24800,
    currentPrice: 22400,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXEeHnLxxZxa9qGg7lidsrXjJBUaKH4RAQBcGEQVsZ7S_bmTCkZCaaaKYNoz27WELUOyd7pdZrVBK8HsLO_-ATLA53RB2cQ_xZ_xX7Rz8kE8QfC1AibrjXGEDFUw_qasaegyUeKMwRcWDBzrddhE5oARFj9iJwuCWekyZYXWvKxnSZM4X2LLuUaGVQtwHqduYyIXQOphwiJK1z8puW9z77lmro_TvF9xLfdrHpUzk-wb4PSCMpOrwBPkuE52ZCXTRdb2XCiofLik8',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCXEeHnLxxZxa9qGg7lidsrXjJBUaKH4RAQBcGEQVsZ7S_bmTCkZCaaaKYNoz27WELUOyd7pdZrVBK8HsLO_-ATLA53RB2cQ_xZ_xX7Rz8kE8QfC1AibrjXGEDFUw_qasaegyUeKMwRcWDBzrddhE5oARFj9iJwuCWekyZYXWvKxnSZM4X2LLuUaGVQtwHqduYyIXQOphwiJK1z8puW9z77lmro_TvF9xLfdrHpUzk-wb4PSCMpOrwBPkuE52ZCXTRdb2XCiofLik8',
      'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1482862549707-f63cb32c5fd9?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80'
    ],
    rating: 4.7,
    reviewsCount: 76,
    description: 'Aproveite a autêntica hospitalidade suíça em Zermatt, a vila livre de carros aos pés do lendário Matterhorn. Esqui alpino em pistas perfeitas e aconchego com lareiras aquecidas de pedra.',
    accommodation: {
      name: 'Mont Cervin Palace Zermatt',
      stars: 4,
      description: 'Com mais de 150 anos de história de excelência, o Mont Cervin Palace acolhe seus hóspedes com elegância tirolesa, banhos de jacuzzi térmicos externos e gastronomia acolhedora alpina de luxo.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXEeHnLxxZxa9qGg7lidsrXjJBUaKH4RAQBcGEQVsZ7S_bmTCkZCaaaKYNoz27WELUOyd7pdZrVBK8HsLO_-ATLA53RB2cQ_xZ_xX7Rz8kE8QfC1AibrjXGEDFUw_qasaegyUeKMwRcWDBzrddhE5oARFj9iJwuCWekyZYXWvKxnSZM4X2LLuUaGVQtwHqduYyIXQOphwiJK1z8puW9z77lmro_TvF9xLfdrHpUzk-wb4PSCMpOrwBPkuE52ZCXTRdb2XCiofLik8',
      amenities: ['Ski-in/Ski-out', 'Jacuzzi Térmica', 'Restaurante Fondue', 'Serviço de Carruagem']
    },
    itinerary: [
      { day: 1, title: 'Passeio de Carruagem e Alta Gastronomia', description: 'Recepção mágica na estação de Zermatt com uma carruagem clássica puxada a cavalos. Jantar de fondue trufado particular.' },
      { day: 2, title: 'Ski VIP Pass Matterhorn', description: 'Acesso prioritário às pistas mais exclusivas do Matterhorn Glacier Paradise com instrutor campeão olímpico dedicado.' },
      { day: 3, title: 'Spa Térmico ao Ar Livre', description: 'Tarde de terapia corporal de chocolate alpino seguida de banho termal sob flocos de neve silenciosos.' }
    ],
    includedExperiences: [
      { icon: 'snowboarding', title: 'Ski Pass Pro ilimitado', description: 'Acesso privativo total guiado à zona transfronteiriça com a Itália.' },
      { icon: 'spa', title: 'Hot Stone Alpine Relief', description: 'Massagem térmica com pedras vulcânicas do pico de Monte Rosa.' }
    ]
  },
  // --- NOVOS PACOTES ADICIONADOS REALISTAS ---
  {
    id: 'pkg-orlando-disney-completa',
    title: 'Disney Completa Orlando',
    destination: 'Orlando',
    country: 'Estados Unidos',
    hotel: "Disney's Pop Century Resort",
    stars: 4,
    flight: 'United Airlines (Voo Direto)',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 12500,
    currentPrice: 11200,
    isPromo: true,
    promoLabel: 'MAIS PROCURADO',
    image: 'https://images.unsplash.com/photo-1597466765990-64ad1c35dafc?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 165,
    description: 'Viva a magia total! Acesso integral com ingressos para Magic Kingdom, EPCOT, Hollywood Studios e Animal Kingdom com os benefícios mágicos de se hospedar dentro do complexo da Disney.'
  },
  {
    id: 'pkg-orlando-disney-premium',
    title: 'Disney Premium Orlando',
    destination: 'Orlando',
    country: 'Estados Unidos',
    hotel: "Disney's Grand Floridian Resort & Spa",
    stars: 5,
    flight: 'American Airlines (Classe Executiva)',
    durationDays: 10,
    durationNights: 9,
    originalPrice: 28900,
    currentPrice: 25200,
    image: 'https://images.unsplash.com/photo-1545231027-63b3f1600758?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 92,
    description: 'Hospedagem luxuosa no hotel de maior prestígio e elegância vitoriana da Disney. Inclui transporte integral exclusivo de monotrilho e experiência premium fura-filas ligada aos parques.'
  },
  {
    id: 'pkg-orlando-disney-universal',
    title: 'Disney + Universal Studios',
    destination: 'Orlando',
    country: 'Estados Unidos',
    hotel: "Universal's Cabana Bay Beach Resort",
    stars: 4,
    flight: 'Delta Air Lines',
    durationDays: 9,
    durationNights: 8,
    originalPrice: 15300,
    currentPrice: 13950,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnRZsZ52ExQG4lMSAjih3uM0kknM0Gavh40CflJIJAbg&s=10',
    rating: 4.9,
    reviewsCount: 140,
    description: 'A união imbatível dos brinquedos mais emocionantes da Universal Studios, de Islands of Adventure e Volcano Bay combinados ao mundo de fantasia dos parques Disney.'
  },
  {
    id: 'pkg-orlando-miami',
    title: 'Orlando + Miami',
    destination: 'Orlando & Miami',
    country: 'Estados Unidos',
    hotel: 'Loews Miami Beach Hotel',
    stars: 4,
    flight: 'LATAM Airlines',
    durationDays: 11,
    durationNights: 10,
    originalPrice: 17900,
    currentPrice: 15800,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUbMyGoJc27KBVhmdTxst8iG9ZG2mKjOv-fkKUb7OkSw&s=10',
    rating: 4.7,
    reviewsCount: 88,
    description: 'Combine as montanhas russas mais desejadas com sol, badalação e ótimas compras no coração de Miami Beach. Aluguel de veículo SUV incluso durante a estadia.'
  },
  {
    id: 'pkg-italia-classica',
    title: 'Itália Clássica',
    destination: 'Roma, Florença & Veneza',
    country: 'Itália',
    hotel: 'Hotel NH Collection Roma Palazzo Cinquecento',
    stars: 5,
    flight: 'ITA Airways',
    durationDays: 9,
    durationNights: 8,
    originalPrice: 19800,
    currentPrice: 18200,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR12rBwgaZl7dWI5_LguJ5vnyfO_7aklM8CCtQZw5nMZw&s=10',
    rating: 4.9,
    reviewsCount: 215,
    description: 'Conecte-se aos maiores patrimônios históricos da humanidade. Passeios pelo Coliseu, os canais charmosos de Veneza e as obras primas do Renascimento florentino.'
  },
  {
    id: 'pkg-italia-premium',
    title: 'Itália Premium',
    destination: 'Roma, Florença, Veneza & Milão',
    country: 'Itália',
    hotel: 'Hotel Principe di Savoia Milan',
    stars: 5,
    flight: 'Lufthansa (Voo Executiva)',
    durationDays: 12,
    durationNights: 11,
    originalPrice: 32500,
    currentPrice: 29500,
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 97,
    description: 'A excelência de viajar pelo melhor do solo italiano. Hospedagem palaciana 5 estrelas, traslados em trem europeu de alta velocidade na primeira classe e guia exclusivo.'
  },
  {
    id: 'pkg-costa-amalfitana',
    title: 'Costa Amalfitana',
    destination: 'Positano & Amalfi',
    country: 'Itália',
    hotel: 'Le Sirenuse Positano',
    stars: 5,
    flight: 'Air France',
    durationDays: 7,
    durationNights: 6,
    originalPrice: 23800,
    currentPrice: 21500,
    image: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 84,
    description: 'Conheça a litorânea mais romântica do mundo. Desfrute da vista límpida mar olhando os vinhedos e casas floridas empilhadas. Inclui um dia de passeio de barco em Capri.'
  },
  {
    id: 'pkg-toscana-premium',
    title: 'Toscana Premium',
    destination: 'Toscana',
    country: 'Itália',
    hotel: 'Castello di Casole, A Belmond Hotel',
    stars: 5,
    flight: 'Lufthansa',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 24500,
    currentPrice: 22800,
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 52,
    description: 'Uma estadia deslumbrante em vinhedos e castelos rústicos de luxo. Inclui visitas culinárias exclusivas, queijos artesanais e vinhos Brunello de altíssima safra.'
  },
  {
    id: 'pkg-paris-romantica',
    title: 'Paris Romântica',
    destination: 'Paris',
    country: 'França',
    hotel: 'Shangri-La Paris',
    stars: 5,
    flight: 'Air France',
    durationDays: 6,
    durationNights: 5,
    originalPrice: 18500,
    currentPrice: 16900,
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 176,
    description: 'O ápice do romantismo com vistas espetaculares à Torre Eiffel. Entradas preferenciais para o Museu do Louvre e um inesquecível jantar de gala a bordo no Rio Sena.'
  },
  {
    id: 'pkg-paris-disney',
    title: 'Paris + Disneyland Paris',
    destination: 'Paris',
    country: 'França',
    hotel: 'Disneyland Hotel Paris',
    stars: 5,
    flight: 'TAP Air Portugal',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 20900,
    currentPrice: 18800,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7enfdO9rU3nkWJmeUZ9ZpqWgkNwSlVGtdlWF0MOYYBg&s=10',
    rating: 4.8,
    reviewsCount: 112,
    description: 'Perfeito para desfrutar o luxo cultural de Paris combinado à diversão do parque com hospedagem premium diretamente ao lado do Castelo de Conto de Fadas da Europa.'
  },
  {
    id: 'pkg-londres-completa',
    title: 'Londres Completa',
    destination: 'Londres',
    country: 'Reino Unido',
    hotel: 'The Savoy',
    stars: 5,
    flight: 'British Airways',
    durationDays: 7,
    durationNights: 6,
    originalPrice: 18200,
    currentPrice: 16500,
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ca1ad?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 131,
    description: 'Vibrante herança imperial. Tenha tours particulares guiados pelo British Museum, a Torre de Londres, a tradicional London Eye e o lendário chá das cinco do Savoy.'
  },
  {
    id: 'pkg-londres-paris',
    title: 'Londres + Paris',
    destination: 'Londres & Paris',
    country: 'Reino Unido & França',
    hotel: 'The Ritz London',
    stars: 5,
    flight: 'British Airways & Trem Eurostar',
    durationDays: 10,
    durationNights: 9,
    originalPrice: 28900,
    currentPrice: 25900,
    image: 'https://images.unsplash.com/photo-1522083165195-3427ee0294abd?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 154,
    description: 'Cruze o canal da mancha a bordo do trem bala Eurostar de primeira classe unindo duas metrópoles espetaculares de palácios, mimos reais e estilo insuperável.'
  },
  {
    id: 'pkg-santorini-mykonos',
    title: 'Santorini e Mykonos',
    destination: 'Santorini & Mykonos',
    country: 'Grécia',
    hotel: 'Myconian Avaton Resort',
    stars: 5,
    flight: 'Aegean Airlines',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 22500,
    currentPrice: 19800,
    image: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 145,
    description: 'Praias maravilhosas, vilarejos de puro branco à caldeira e baladas sofisticadas nas ilhas gregas mais desejadas internacionalmente. Passeio de catamarã exclusivo.'
  },
  {
    id: 'pkg-dubai-luxo',
    title: 'Dubai Luxo',
    destination: 'Dubai',
    country: 'EAU',
    hotel: 'Burj Al Arab Jumeirah',
    stars: 5,
    flight: 'Emirates Airlines (Primeira Classe)',
    durationDays: 6,
    durationNights: 5,
    originalPrice: 38500,
    currentPrice: 34900,
    image: 'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 110,
    description: 'Conheça o ápice absoluto do turismo no único hotel de conceito 7 estrelas no mundo, com mordomo privativo, suíte de dois andares e praias de areias douradas.'
  },
  {
    id: 'pkg-dubai-abudhabi',
    title: 'Dubai e Abu Dhabi',
    destination: 'Dubai & Abu Dhabi',
    country: 'EAU',
    hotel: 'Emirates Palace Mandarin Oriental',
    stars: 5,
    flight: 'Emirates Airlines',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 25900,
    currentPrice: 22800,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 121,
    description: 'Uma incrível odisseia do deserto moderno árabe ao palácio real de Abu Dhabi. Ingressos privativos para a belíssima Mesquita Sheikh Zayed e atrações inclusas.'
  },
  {
    id: 'pkg-maldivas-premium',
    title: 'Maldivas Premium',
    destination: 'Maldivas',
    country: 'Maldivas',
    hotel: 'Gili Lankanfushi Maldives',
    stars: 5,
    flight: 'Qatar Airways',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 31500,
    currentPrice: 28900,
    image: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 116,
    description: 'Descanse em vilas suspensas ecológicas flutuando sobre lagoas marinhas límpidas e corais deslumbrantes. Atendimento personalizado de primeira grandeza.'
  },
  {
    id: 'pkg-maldivas-luademel',
    title: 'Lua de Mel nas Maldivas',
    destination: 'Maldivas',
    country: 'Maldivas',
    hotel: 'One&Only Reethi Rah',
    stars: 5,
    flight: 'Emirates Airlines',
    durationDays: 10,
    durationNights: 9,
    originalPrice: 39500,
    currentPrice: 36800,
    image: 'https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 139,
    description: 'O refúgio definitivo do amor. Decoração temática romântica, piquenique em bancos de areia desertos e massagem relaxante integrada à beira dos recifes de coral.'
  },
  {
    id: 'pkg-japao-completo',
    title: 'Japão Completo',
    destination: 'Tóquio, Kyoto & Osaka',
    country: 'Japão',
    hotel: 'Aman Tokyo',
    stars: 5,
    flight: 'ANA All Nippon Airways',
    durationDays: 12,
    durationNights: 11,
    originalPrice: 42000,
    currentPrice: 38900,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 201,
    description: 'Conecte-se com o modernismo extremo no centro de Tóquio, a tranquilidade pacífica de Kyoto, templos budistas milenares e castelos feudais inesquecíveis.'
  },
  {
    id: 'pkg-fernando-noronha',
    title: 'Fernando de Noronha',
    destination: 'Fernando de Noronha',
    country: 'Brasil',
    hotel: 'Pousada Maria Bonita Noronha',
    stars: 5,
    flight: 'Azul Linhas Aéreas',
    durationDays: 6,
    durationNights: 5,
    originalPrice: 12900,
    currentPrice: 11500,
    image: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 167,
    description: 'Santuário natural único com as praias mais famosas e águas límpidas de mergulho do Brasil. Perfeito para observar golfinhos selvagens com máxima calmaria.'
  },
  {
    id: 'pkg-gramado-premium',
    title: 'Gramado Premium',
    destination: 'Gramado',
    country: 'Brasil',
    hotel: 'Hotel Ritta Höppner',
    stars: 5,
    flight: 'Voe Azul para Porto Alegre',
    durationDays: 5,
    durationNights: 4,
    originalPrice: 6500,
    currentPrice: 5800,
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 124,
    description: 'Acolhimento de primeira classe na serra mais elegante da América do Sul. Fondue, chocolates trufados artesanais e passeios a vinícolas clássicas.'
  },
  {
    id: 'pkg-rio-premium',
    title: 'Rio de Janeiro Premium',
    destination: 'Rio de Janeiro',
    country: 'Brasil',
    hotel: 'Copacabana Palace, A Belmond Hotel',
    stars: 5,
    flight: 'Voo LATAM',
    durationDays: 5,
    durationNights: 4,
    originalPrice: 8500,
    currentPrice: 7600,
    image: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 198,
    description: 'Sinta o luxo icônico e refinamento na Praia de Copacabana. Desfrute de mimos de primeira no Copa e traslado VIP com fura-filas para o belo Cristo Redentor.'
  },
  {
    id: 'pkg-cancun-allinclusive',
    title: 'Cancún All Inclusive',
    destination: 'Cancún',
    country: 'México',
    hotel: 'TRS Coral Hotel Luxury Resort',
    stars: 5,
    flight: 'Aeroméxico',
    durationDays: 7,
    durationNights: 6,
    originalPrice: 13900,
    currentPrice: 12500,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 189,
    description: 'Frente para o mar do Caribe Mexicano em sistema de alta gastronomia e drinks finos à beira-mar livre, sem limite de consumo. Ótimos passeios para Chichén Itzá.'
  },
  {
    id: 'pkg-puntacana',
    title: 'Punta Cana Resort',
    destination: 'Punta Cana',
    country: 'República Dominicana',
    hotel: 'Lopesan Costa Bávaro Resort',
    stars: 5,
    flight: 'COPA Airlines',
    durationDays: 7,
    durationNights: 6,
    originalPrice: 12500,
    currentPrice: 11200,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 147,
    description: 'Resort de extensas piscinas infinitas integradas com coqueiros perfeitos e areia de coral macia e claríssima, ideal para esquecer a rotina diária.'
  },
  {
    id: 'pkg-lisboa-porto',
    title: 'Lisboa e Porto',
    destination: 'Lisboa & Porto',
    country: 'Portugal',
    hotel: 'The Yeatman Hotel Wine Resort',
    stars: 5,
    flight: 'TAP Air Portugal',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 16900,
    currentPrice: 15300,
    image: 'https://images.unsplash.com/photo-1509840144521-17d12a51b28e?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 182,
    description: 'Combine ruelas medievais, alta gastronomia portuguesa contemporânea, o maravilhoso Rio Douro e degustações orientadas por sommeliers nos melhores vinhedos do Porto.'
  },
  {
    id: 'pkg-barcelona-madrid',
    title: 'Barcelona e Madrid',
    destination: 'Barcelona & Madrid',
    country: 'Espanha',
    hotel: 'Mandarin Oriental Barcelona',
    stars: 5,
    flight: 'Iberia',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 18900,
    currentPrice: 16800,
    image: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 163,
    description: 'Embeleze-se com a arquitetura magnífica de Gaudí e a elite comercial do Palácio Real espanhol. Inclui visitas preferenciais ao Parque Güell e Museu do Prado.'
  },
  {
    id: 'pkg-suica-premium',
    title: 'Suíça Premium',
    destination: 'Zurique & Interlaken',
    country: 'Suíça',
    hotel: 'Victoria-Jungfrau Grand Hotel',
    stars: 5,
    flight: 'Swiss International Air Lines',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 28500,
    currentPrice: 25900,
    image: 'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 95,
    description: 'Montanhas idílicas dos Alpes e águas espelhadas suíças. Desfrute de viagens maravilhosas com o passe de primeira classe panorâmico de trem GoldenPass Express.'
  },
  {
    id: 'pkg-egito-historico',
    title: 'Egito Histórico',
    destination: 'Cairo & Luxor',
    country: 'Egito',
    hotel: 'Four Seasons Hotel Cairo at Nile Plaza',
    stars: 5,
    flight: 'EgyptAir',
    durationDays: 9,
    durationNights: 8,
    originalPrice: 20900,
    currentPrice: 18500,
    image: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 135,
    description: 'Arqueologia inigualável com guias egiptólogos especializados. Visite templos milenares no vale dos reis e deslumbre-se com cruzeiro panorâmico no Rio Nilo.'
  },
  {
    id: 'pkg-turquia',
    title: 'Turquia Completa',
    destination: 'Istambul & Capadócia',
    country: 'Turquia',
    hotel: 'Museum Hotel Cappadocia',
    stars: 5,
    flight: 'Turkish Airlines',
    durationDays: 9,
    durationNights: 8,
    originalPrice: 22800,
    currentPrice: 19800,
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 178,
    description: 'Vivencie a Capadócia com os famosos voos de balão coloridos no nascer do sol e a exuberante herança otomana das belas mesquitas de Istambul.'
  },
  {
    id: 'pkg-tailandia',
    title: 'Tailândia Premium',
    destination: 'Bangkok & Phuket',
    country: 'Tailândia',
    hotel: 'Keemala Phuket',
    stars: 5,
    flight: 'Qatar Airways',
    durationDays: 11,
    durationNights: 10,
    originalPrice: 24500,
    currentPrice: 22500,
    image: 'https://images.unsplash.com/photo-1528181304800-2f1908d98981?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 151,
    description: 'Descubra sanduários dourados e vilas suspensas ecológicas no Keemala Phuket. Inclui barcos de velocidade privativos pelas belas águas de Phi Phi Islands.'
  },
  {
    id: 'pkg-cruzeiro-caribe',
    title: 'Cruzeiro pelo Caribe',
    destination: 'Nassau, Bahamas & Caribe',
    country: 'Caribe',
    hotel: 'Icon of the Seas (Suíte Superior)',
    stars: 5,
    flight: 'Delta Air Lines',
    durationDays: 8,
    durationNights: 7,
    originalPrice: 18500,
    currentPrice: 16900,
    image: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 119,
    description: 'Aventure-se a bordo do navio mais formidável do mundo. Paradas VIP em praias exuberantes, parques aquáticos incríveis e cassinos de classe mundial em Nassau.'
  }
].map(pkg => {
  // Para evitar overhead de linhas repetidas no arquivo garantindo compacidade,
  // injetamos estruturas ricas de itinerário e acomodação completas dinamicamente para os novos pacotes!
  return {
    ...pkg,
    images: pkg.images || [pkg.image, 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&auto=format&fit=crop&q=80'],
    accommodation: pkg.accommodation || {
      name: `${pkg.hotel}`,
      stars: pkg.stars,
      description: `Hospede-se com máximo refúgio e requinte impecável no ${pkg.hotel}. Oferece serviço de classe mundial personalizado, gastronomia gourmet, ambientes amplos de spa e lazer inigualável no destino de ${pkg.destination}.`,
      image: pkg.image,
      amenities: ['Wi-Fi de Alta Velocidade', 'Serviço de Quarto Premium', 'Spa & Wellness', 'Piscina Exclusiva', 'Ar Condicionado']
    },
    itinerary: pkg.itinerary || [
      { day: 1, title: 'Chegada e Recepção Exclusiva', description: `Traslado privado no aeroporto de ${pkg.destination} com motorista executivo, check-in premium e coquetel especial de boas-vindas.` },
      { day: 2, title: 'Tour Cultural & Pontos Memoráveis', description: `Passeio guiado privativo de dia inteiro conhecendo os monumentos, segredos históricos e melhores pontos de interesse locais.` },
      { day: 3, title: 'Experiência Livre & Gastronomia Gourmet', description: `Desfrute de um dia inteiramente ao seu tempo para compras, lazer ou para relaxar no spa do hotel seguido de um jantar especial reservado.` }
    ],
    includedExperiences: pkg.includedExperiences || [
      { icon: 'explore', title: 'Tour Privativo Especial', description: 'Visitas exclusivas com guias credenciados locais integrados.' },
      { icon: 'stars', title: 'Kit Boas-Vindas Exclusive', description: 'Tratamento VIP, mimos finos do hotel e transfers de entrada e saída inclusos.' }
    ]
  };
});

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'MDV-2026-78542',
    packageId: 'pkg-paris-romance',
    packageTitle: 'Escapada Romântica em Paris',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWVYM9fX2VtZFjic9vrjl-D9J3AjkMeh7_GK4UR16L8FMeud7a_QJ5b7pBJYS_nCg-pBpeHsV8ThR2qSycRRow8YHMugoMayzxvP5H9QyygiD82422pe0UtppTjA0dBD0Fy5YyW9P622I5_xAXTcps1LxS2nOeG5Cu7LwBYyCXDcvJybdIEJb0jNip8ifVClaSEW02WCjwCT8uDb5Xq5X5K0r5VdLo0Xas05ZZhtdLjuleiFMXmpUchA_FI9-yHzVDeoqOAoyD6QA',
    startDate: '12 Nov 2026',
    endDate: '18 Nov 2026',
    adultsCount: 2,
    childrenCount: 0,
    status: 'Confirmada',
    paymentMethod: 'À Vista',
    totalPaid: 25507.50,
    daysToTrip: 20,
    passengers: [
      {
        fullName: 'Carlos Eduardo Silva',
        cpf: '123.456.789-00',
        document: 'RG 45.678.912-X',
        birthDate: '15/08/1985',
        nationality: 'Brasil',
        gender: 'Masculino'
      }
    ]
  },
  {
    id: 'VE-883291',
    packageId: 'pkg-maldivas',
    packageTitle: 'Retiro nas Maldivas',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA_EtYtDHGcIdOpZrTJe6NqaLjmqVvzXGJtqKG8mcUD9-uAPR67n_44JptrV1UGK3FrXHphlXG-7iX1_94zWTZ0N95raSqtp6mku6CChzH-FcWKYurJV_UoAJYw2zJ1RGYhkjJaf-7-NWFplvA3nzY5ady358cHyUu9NZxJJ1XSjPF3nhxwJgRzcntjh0VIi2vGRnuspmGpYd14_aqZDZFfw3C_3qahy0ybLtsaoGVGUeSgVK6Px1DUZddKlHHMAYD4P8tYQxCzwQg',
    startDate: '05 Jan 2025',
    endDate: '12 Jan 2025',
    adultsCount: 2,
    childrenCount: 0,
    status: 'Pendente Pagamento',
    paymentMethod: 'A Confirmar',
    totalPaid: 35800.00,
    daysToTrip: 45,
    passengers: [
      {
        fullName: 'Carlos Eduardo Silva',
        cpf: '123.456.789-00',
        document: 'RG 45.678.912-X',
        birthDate: '15/08/1985',
        nationality: 'Brasil',
        gender: 'Masculino'
      }
    ]
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-ana',
    userName: 'Ana Silva',
    userAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBbsIs-uIjT_9aoLeneBRAKm0H5o6czDEpE1xKWQtoLLZqVhbCdRg7-FJ4FzKEA44Q7HDCku133U-mRJXn0ZrMKHlbAuGTEy-OYHtWPypY397wYF-yk7dAPhKyQF64RDXavntPaR-eH8ygr4F2yCkfhrgZNECALC4lQJjT_rMMv7RfLJ8W6LwPcZG392z3oJFCDmp1tBbA5L4sy-V5sOr057yRbrCH_k6wkizT9RjUBtr48O_ZHDt_a2rx5yE_ZXnBMKIp2mQyljSc',
    packageName: 'Maldivas - Resort Exclusivo',
    rating: 5,
    comment: 'A viagem dos sonhos! O resort nas Maldivas superou todas as expectativas. A organização da Angel Voyage foi impecável, desde o voo até os passeios locais. Recomendo de olhos fechados.',
    date: '12 de Outubro, 2024'
  },
  {
    id: 'rev-carlos',
    userName: 'Carlos Mendes',
    userAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCqpyxZ8sW8rKUaYGQa0X-k2yTr41U6pj6Sc3ojfd3hCAopuTwdCznhTZFfUlBdxFpcY1hMHjeRU7QEqvXuDqOfscrh9beAThX1JgvViIuAnU9kubFmtQKvGyYyeCwVaADY5LtKzV5Qwk9TUZjBYwhfFpcpB9FiHfvxbECciwnt0vUqDP5utUfWZxAMtbIK2VcQU1B_Qm2pNfNhQCl77hv8VNErvhGUxz56zXtdHnGB676oIeHnqboN7BthIebWKrlnVlEa0jshOag',
    packageName: 'Paris - Romance e Cultura',
    rating: 4,
    comment: 'Excelente pacote. O hotel tinha uma vista linda para a Torre Eiffel. Tivemos um pequeno atraso no transfer do aeroporto, mas a equipe resolveu rapidamente.',
    date: '05 de Outubro, 2024'
  },
  {
    id: 'rev-mariana',
    userName: 'Mariana Costa',
    userAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWzWbp4mt6UJCUfwSz5bkRzJMUCLRkC5E3QpftIq3muKKnjn5Lpx19CINyNXU7ib5L2183j_hP6VHhcrECaPkboQDeIUFPhtGf3pVQszxHjshqG1pnUWIJgyiwpAKEUTUOzyb1fcA5T9utna2AXpzq78BaPanHoghBMlYmyNEYt1HeH0v64iyZhrw6QVhJTXyt6sztiJSlEYpqHkIgBmvBow_pdpKK3ImRDSNW0E53zsYWEMRAf0ratwWJWabWBJHNNQ4_JhQHWa0',
    packageName: 'Tóquio - Aventura Urbana',
    rating: 5,
    comment: 'Uma imersão cultural fantástica. O guia sugerido pela agência falava português perfeito e nos levou a lugares incríveis que não estavam nos guias turísticos comuns. Serviço de luxo.',
    date: '28 de Setembro, 2024'
  }
];
